version: '3.6'

services:

  django:
    container_name: django
    build: django/
    image: nursery_django
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/public/media
    command: > 
      bash -c "pipenv run python3 manage.py makemigrations --merge
      && pipenv run python3 manage.py collectstatic --no-input
      && pipenv run gunicorn --bind=0.0.0.0:8000 main.wsgi:application"
    restart: on-failure
    networks:
      - nginx_network

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/public/media
      - ./services/data/certbot/conf:/etc/letsencrypt
      - ./services/data/certbot/www:/var/www/certbot
    restart: on-failure
    depends_on:
      - django
    networks:
      - nginx_network

  certbot:
    image: certbot/certbot
    volumes:
        - ./services/data/certbot/conf:/etc/letsencrypt
        - ./services/data/certbot/www:/var/www/certbot


networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume: