version: '3.7'

services:

  django:
    container_name: django
    build: django/
    image: nursery_django
    env_file: .env
    volumes:
      - ./django/project/:/app/
      - static_volume:/app/staticfiles
      - media_volume:/app/public/media
    command: > 
      bash -c "pipenv run python3 manage.py makemigrations --merge
      && pipenv run python3 manage.py collectstatic --no-input
      && pipenv run gunicorn --bind=0.0.0.0:8000 main.wsgi:application"
    restart: on-failure
    networks:
      - nginx_network
    links:
      - redis:redis


  nginx:
    build: ./nginx
    container_name: nginx
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./ssl:/ssl
      - static_volume:/app/staticfiles
    networks:
      - nginx_network
    depends_on:
      - django

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

networks:
  nginx_network:
    driver: bridge


volumes:
  static_volume:
  media_volume:
  redis_volume:

