# https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c
version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: on-failure

  django:
    depends_on:
      - db
    networks:
      - db_network
      - selenium_network

  selenium_hub:
    container_name: selenium_hub
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - selenium_network

  selenium_chrome:
    container_name: selenium_chrome
    image: selenium/node-chrome-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5900:5900"
    depends_on:
      - selenium_hub
    networks:
      - selenium_network
      - nginx_network

volumes:
  postgres-data:

networks:
  db_network:
    driver: bridge
  selenium_network:
    driver: bridge